"""Export the I2P Address Book as interactive HTML + hosts.txt."""

from __future__ import annotations

import json
import pathlib
import sqlite3
from datetime import datetime, timezone

from .integration import get_address_book


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_TEMPLATE_DIR = pathlib.Path(__file__).parent / "browse_template.html"


def generate_address_book_txt(db_path: str, output_dir: str) -> pathlib.Path:
    """Generate an I2P router addressbook-style TXT file.

    Uses the ``address_book`` view for all destinations (probe-only and SUSI)
    and enriches with raw dest_data blobs from the ``targets`` table when
    available.  Outputs in the classic hosts.txt format used by I2P routers'
    /susidns/export so it can be round-tripped back into a router's address
    book or imported by any SUSI DNS consumer.

    Format per entry:
        # dns_name: b32_addr.b32.i2p [STATUS] probed=TIMESTAMP
        dns_name=base64_destination_blob_or_b32.i2p

    Args:
        db_path: Path to the I2P Indexer SQLite database.
        output_dir: Directory to write the TXT file into (created if missing).

    Returns:
        Absolute path to the generated ``hosts.txt``.
    """
    # 1. Fetch all rows from address_book for reachability/metadata
    raw_rows = get_address_book(db_path)
    raw_rows.sort(key=lambda r: (r.get("dns_name") or "").lower())

    total = len(raw_rows)
    reachable_count = sum(1 for r in raw_rows if r.get("reachable"))
    down_count = total - reachable_count

    # 2. Build dns_name -> dest_data map from targets table
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    cur.execute("""
        SELECT DISTINCT i2p_dns_name, dest_data
        FROM targets
        WHERE LENGTH(dest_data) > 0
    """)
    dest_map: dict[str, str] = {}
    for dns, blob in cur.fetchall():
        if dns and blob:
            dest_map[dns] = blob
    conn.close()

    # 3. Header lines — match router export format exactly
    now_utc = datetime.utcnow()
    host_lines: list[str] = [
        f"# Address book: I2P Indexer (auto-generated by discovery probes)",
        f"# Exported: {now_utc.strftime('%a %b %d %H:%M:%S GMT %Y')}",
        f"# {total} entries",
    ]

    # 4. Per-entry: comment + key=value in SUSI DNS hosts.txt format
    for row in raw_rows:
        dns_name = row.get("dns_name", "") or ""
        # b32_addr from address_book already includes the .b32.i2p suffix
        b32_full = (row.get("b32_addr") or "").strip()

        # Comment line mirrors router export: "# name: b32.b32.i2p"
        if b32_full:
            comment = f"#{dns_name}: {b32_full}"
        else:
            comment = f"#{dns_name}"

        # Value line: dns_name=base64_blob (empty if no blob available)
        value_blob = dest_map.get(dns_name) or ""
        
        host_lines.append(comment)
        host_lines.append(f"{dns_name}={value_blob}")

    # 5. Write to output directory as hosts.txt (SUSI DNS importable format)
    out_path = pathlib.Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    target = out_path / "hosts.txt"
    target.write_text("\n".join(host_lines) + "\n", encoding="utf-8")
    return target.resolve()


def generate_index_html(output_dir: str) -> pathlib.Path:
    """Generate a project landing page with links to all exports and GitHub.

    Writes *index.html* into *output_dir*.

    Returns:
        Absolute path to the generated ``index.html``.
    """
    now_utc = datetime.utcnow()
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>I2P Indexer — Eepsite Discovery &amp; Cataloging</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
*,*::before,*::after{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:'Courier New',monospace;font-size:14px;color:#e0e0e0;
    background:#0a0a0f;line-height:1.6;max-width:820px;margin:0 auto;padding:32px 16px}}
h1{{font-size:24px;color:#fff;margin-bottom:4px;letter-spacing:-0.5px}}
h2{{font-size:16px;color:#aaa;margin:28px 0 8px;border-bottom:1px solid #222;padding-bottom:4px}}
h3{{font-size:13px;color:#888;margin:16px 0 6px}}
p{{margin:8px 0}}
a{{color:#5b9;text-decoration:none}} a:hover{{color:#7df;text-decoration:underline}}
code{{background:#14141a;padding:2px 6px;border-radius:3px;font-size:13px;color:#ccc}}
.hero{{text-align:center;padding:48px 0 32px;border-bottom:1px solid #222;margin-bottom:32px}}
.hero h1{{font-size:32px;margin-bottom:8px}}
.hero .subtitle{{color:#888;font-size:15px;max-width:600px;margin:0 auto}}
.hero .emoji{{font-size:48px;display:block;margin-bottom:16px}}
.links{{display:grid;gap:12px;margin:16px 0}}
.link-card{{display:flex;align-items:center;gap:12px;padding:14px 16px;
    background:#111;border:1px solid #2a2a30;border-radius:6px;text-decoration:none;color:#e0e0e0}}
.link-card:hover{{border-color:#5b9;background:#151520}}
.link-card .icon{{font-size:24px;flex-shrink:0;width:36px;text-align:center}}
.link-card .label{{font-weight:bold;font-size:14px}}
.link-card .desc{{font-size:12px;color:#888;margin-top:2px}}
.features{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;margin:16px 0}}
.feature{{padding:14px;background:#111;border:1px solid #222;border-radius:6px}}
.feature h3{{margin:0 0 6px;color:#ccc}}
.feature p{{font-size:13px;color:#888;margin:0}}
pre{{background:#14141a;padding:12px;border-radius:6px;overflow-x:auto;font-size:13px;margin:8px 0;border:1px solid #222}}
footer{{text-align:center;margin-top:48px;padding:16px;border-top:1px solid #222;
    font-size:12px;color:#555}}
</style>
</head>
<body>

<div class="hero">
  <span class="emoji">🦉</span>
  <h1>I2P Indexer</h1>
  <p class="subtitle">Client-side discovery and cataloging of I2P eepsites — probes, classifies, and exports a searchable address book from a local router daemon.</p>
</div>

<h2>Explore the Data</h2>
<div class="links">
  <a class="link-card" href="address_book.html">
    <span class="icon">🔍</span>
    <div><div class="label">Address Book</div><div class="desc">Interactive browse UI with sortable grid, search, filters, timeline, and per-entry detail panels.</div></div>
  </a>

  <a class="link-card" href="hosts.txt">
    <span class="icon">📋</span>
    <div><div class="label">Hosts Export</div><div class="desc">Plain text <code>dns=base64_blob</code> format matching SUSI DNS export — importable by I2P routers and other tools.</div></div>
  </a>

  <a class="link-card" href="https://github.com/BuboTheWise/I2P-Indexer">
    <span class="icon">⚡</span>
    <div><div class="label">Source on GitHub</div><div class="desc">View the code, report issues, or contribute extractors and sweep configurations.</div></div>
  </a>
</div>

<h2>What It Does</h2>
<div class="features">
  <div class="feature">
    <h3>B32-First Probing</h3>
    <p>Direct <code>*.b32.i2p</code> requests that bypass SU3/SUSI DNS — dramatically faster for dead targets.</p>
  </div>
  <div class="feature">
    <h3>Content Classification</h3>
    <p>Plugin-based extractors auto-classify sites into forums, blogs, marketplaces, wikis, and more.</p>
  </div>
  <div class="feature">
    <h3>Local Translation</h3>
    <p>Non-English summaries translated via Ollama (HY-MT2) — no external API calls required.</p>
  </div>
  <div class="feature">
    <h3>Sweep Filters</h3>
    <p>Probe subsets: reachable-only, needs-review, by content type, or crawl linked sites.</p>
  </div>
  <div class="feature">
    <h3>Persistent SQLite Store</h3>
    <p>All results survive across runs — query, re-probe, and track address drift over time.</p>
  </div>
  <div class="feature">
    <h3>Eepsite Export</h3>
    <p>Generate static HTML + text exports for hosting on I2P proxy servers with zero backend dependency.</p>
  </div>
</div>

<h2>License</h2>
<p><a href="https://github.com/BuboTheWise/I2P-Indexer/blob/master/LICENSE">MIT</a> — free for discovery, not surveillance.</p>

<footer>
  Generated by <a href="https://github.com/BuboTheWise/I2P-Indexer">I2P Indexer</a> · Exported {now_utc.strftime('%Y-%m-%d %H:%M UTC')}
</footer>

</body>
</html>"""

    out_path = pathlib.Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    target = out_path / "index.html"
    target.write_text(html, encoding="utf-8")
    return target.resolve()


# ---------------------------------------------------------------------------
# Enhanced browse UI (tabs, timeline, filters, language detection)
# ---------------------------------------------------------------------------

def _query_entries(db_path: str) -> list[dict]:
    """Fetch address_book rows and shape them for the enhanced browse UI JSON.

    Includes ``detected_lang`` and ``flags`` which the enhanced template consumes
    for filter dropdowns and row detail panels.  Since the ``address_book`` view
    does not expose these as top-level columns, we query the underlying
    discoveries table directly to get the latest probe per destination.
    """
    conn = sqlite3.connect(db_path)
    try:
        cur = conn.cursor()
        # Get all rows from address_book view for base data
        ab_rows = get_address_book(db_path)

        # Build a mapping from ident_hash_hex to the actual detected_lang/flags
        # by querying discoveries for the latest probe per destination
        entries: list[dict] = []
        for r in ab_rows:
            # Parse flags JSON safely (DB stores it as a JSON string)
            flags_raw = r.get("flags")
            if isinstance(flags_raw, str):
                try:
                    flags_val = json.loads(flags_raw)
                except (json.JSONDecodeError, TypeError):
                    flags_val = []
            else:
                flags_val = flags_raw or []

            detected_lang = r.get("detected_lang", "") or ""
            # If the view didn't carry detected_lang as a column, we need to
            # fetch it from discoveries.  Try direct lookup first; if None/empty
            # then do a per-hash lookup.
            if not detected_lang:
                ident = r.get("ident_hash_hex", "")
                if ident:
                    cur2 = conn.cursor()
                    cur2.execute(
                        "SELECT detected_lang FROM discoveries "
                        "WHERE ident_hash_hex = ? ORDER BY probed_at DESC LIMIT 1",
                        (ident,),
                    )
                    hit = cur2.fetchone()
                    if hit and hit[0]:
                        detected_lang = hit[0]

            entries.append({
                "dns_name": r.get("dns_name", "") or "",
                "b32_addr": r.get("b32_addr", "") or "",
                "title": r.get("title", "") or "",
                "content_type": r.get("content_type", "") or "",
                "content_summary": (r.get("content_summary") or "").replace("\n", " "),
                "deep_site_type": r.get("deep_site_type", "") or "",
                "deep_purpose": (r.get("deep_purpose", "") or "").replace("\n", " "),
                "deep_analyzed_at": r.get("deep_analyzed_at", "") or "",
                "deep_analysis_json": r.get("deep_analysis", ""),
                "reachable": bool(r.get("reachable", False)),
                "last_probed_utc": r.get("last_probed_utc", "") or "",
                "response_time_sec": r.get("response_time_sec") or 0,
                "body_length": r.get("body_length") or 0,
                "bandwidth_kbps": r.get("bandwidth_kbps"),
                "detected_lang": detected_lang,
                "found_links": (r.get("found_links") or "[]"),
                "flags": flags_val,
                "interest_score": r.get("interest_score"),
                "interest_reasons": (r.get("interest_reasons", "") or ""),
                "content_depth": r.get("content_depth") or 0.0,
                "stability_index": r.get("stability_index") or 0.0,
            })

        return entries
    finally:
        conn.close()


def _query_reachability_series(db_path: str, bucket: str = 'hour') -> list[dict]:
    """Aggregate probe events into hourly buckets for the reachability trends chart.

    Returns a list of dicts with keys:
      - ts_utc: ISO-ish timestamp string for the bucket start (e.g. '2026-08-05 10:00')
      - total_probes: number of probe events in this bucket
      - reachable: number of probes that reached their destination
      - unreachable: number that did not
      - pct: reachability percentage (0-100)

    The aggregation window is driven by *bucket* ('hour' or 'day').  Hourly gives
    finer-grained sparkline data; daily collapses to one point per calendar day.
    """
    conn = sqlite3.connect(db_path)
    try:
        label = "strftime('%Y-%m-%d %H:00', datetime(probed_at, 'unixepoch'))"
        if bucket == 'day':
            label = "DATE(datetime(probed_at, 'unixepoch'))"

        cur = conn.cursor()
        cur.execute(f"""
            SELECT {label} AS ts_utc,
                   COUNT(*)                        AS total_probes,
                   SUM(CASE WHEN reachable=1 THEN 1 ELSE 0 END) AS reachable,
                   SUM(CASE WHEN reachable=0 THEN 1 ELSE 0 END) AS unreachable
            FROM discoveries
            GROUP BY {label}
            ORDER BY ts_utc ASC
        """)

        results: list[dict] = []
        for ts_utc, total, reached, unreach in cur.fetchall():
            pct_val = round(100.0 * reached / total) if total > 0 else 0.0
            # Include unique destination count per bucket (more meaningful than raw probe count)
            results.append({
                "ts_utc": ts_utc,
                "total_probes": total,
                "reachable": reached,
                "unreachable": unreach,
                "pct": pct_val,
            })
        return results
    finally:
        conn.close()


def _query_timeline(db_path: str) -> list[dict]:
    """Fetch the latest discovery per destination for the timeline tab.

    Returns one row per *ident_hash_hex* showing when it was last probed,
    whether it was reachable, and the HTTP status code — exactly what the
    enhanced template's timeline column expects.  Uses ``b32_addr`` as a
    readable fallback when ``i2p_dns_name`` is empty.
    """
    conn = sqlite3.connect(db_path)
    try:
        cur = conn.cursor()
        cur.execute("""
            SELECT d.i2p_dns_name,
                   CASE WHEN d.reachable THEN 1 ELSE 0 END AS reachable,
                   d.status_code,
                   datetime(d.probed_at, 'unixepoch') AS probed_at_utc
            FROM discoveries d
            INNER JOIN (
                SELECT ident_hash_hex, MAX(probed_at) AS max_probed
                FROM discoveries GROUP BY ident_hash_hex
            ) latest ON d.ident_hash_hex = latest.ident_hash_hex
                    AND d.probed_at = latest.max_probed
            ORDER BY d.probed_at DESC
        """)
        results: list[dict] = []
        for dns_name, reachable, status_code, probed_at_utc in cur.fetchall():
            # Use b32_addr as fallback when i2p_dns_name is empty/missing
            if not dns_name:
                cur2 = conn.cursor()
                cur2.execute(
                    "SELECT b32_addr FROM discoveries "
                    "WHERE ident_hash_hex = (SELECT ident_hash_hex FROM discoveries "
                    "  WHERE probed_at = ? LIMIT 1) LIMIT 1",
                    (datetime.strptime(probed_at_utc, "%Y-%m-%d %H:%M:%S")
                     .replace(tzinfo=timezone.utc).timestamp(),),
                )
                hit = cur2.fetchone()
                dns_name = hit[0] if hit else ""
            results.append({
                "dns_name": dns_name or "",
                "reachable": reachable,
                "status_code": status_code,
                "probed_at_utc": probed_at_utc,
            })
        return results
    finally:
        conn.close()


def generate_address_book_html(
    db_path: str,
    output_dir: str,
    template_path: pathlib.Path | None = None,
) -> pathlib.Path:
    """Generate the interactive browse UI HTML with tabs, timeline, and filters.

    Uses ``browse_template.html`` from the source tree which provides a rich
    interface — tabbed navigation, interactive timeline view, type/language/
    status filters, row expansion panels, interest scores, and dark theme
    matching the project style guide.

    Args:
        db_path: Path to the I2P Indexer SQLite database.
        output_dir: Directory to write the HTML file into (created if missing).
        template_path: Optional explicit path to the browse template.
            Defaults to ``src/browse_template.html`` alongside this module.

    Returns:
        Absolute path to the generated ``address_book.html``.
    """
    # 1. Load template
    tmpl = template_path or _TEMPLATE_DIR
    html_template = tmpl.read_text(encoding="utf-8")

    # 2. Fetch data
    entries = _query_entries(db_path)
    items_timeline = _query_timeline(db_path)
    series = _query_reachability_series(db_path, bucket='hour')

    # 3. Serialize JSON payloads
    entries_json = json.dumps(entries, ensure_ascii=False)
    timeline_json = json.dumps(items_timeline, ensure_ascii=False)
    series_json = json.dumps(series, ensure_ascii=False)

    # Timestamp for header/footer
    export_ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")

    # 4. Render template by replacing placeholders
    html = (
        html_template
        .replace("__ENTRIES_JSON__", entries_json)
        .replace("__TIMELINE_JSON__", timeline_json)
        .replace("__REACHABILITY_SERIES_JSON__", series_json)
        .replace("__EXPORT_TS__", export_ts)
    )

    # 5. Write to output directory as address_book.html (canonical name)
    out_path = pathlib.Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    target = out_path / "address_book.html"
    target.write_text(html, encoding="utf-8")
    return target.resolve()
